### ISSUE TITLE
当我将cfenet300_vgg16.py文件中的pretrained改为cfenet300_vgg16_coco.pth[200多MB]的时候因为模型缺少参数报错了

### ISSUE THREAD

**Issue by gittigxuy** [qijiezhao/CFENet#2]
请问如何修改

**Comment by gittigxuy** [comment]
Loading base network...
Traceback (most recent call last):
  File "train.py", line 48, in <module>
    net.init_model(cfg.model.pretrained)
  File "/home/test/code/CFENet/cfenet.py", line 134, in init_model
    self.base.load_state_dict(base_weights)
  File "/home/test/.pyenv/versions/3.6.1/lib/python3.6/site-packages/torch/nn/modules/module.py", line 719, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for ModuleList:
	Missing key(s) in state_dict: "0.weight", "0.bias", "2.weight", "2.bias", "5.weight", "5.bias", "7.weight", "7.bias", "10.weight", "10.bias", "12.weight", "12.bias", "14.weight", "14.bias", "17.weight", "17.bias", "19.weight", "19.bias", "21.weight", "21.bias", "24.weight", "24.bias", "26.weight", "26.bias", "28.weight", "28.bias", "31.weight", "31.bias", "33.weight", "33.bias". 
	Unexpected key(s) in state_dict: "module.base.0.weight", "module.base.0.bias", "module.base.2.weight", "module.base.2.bias", "module.base.5.weight", "module.base.5.bias", "module.base.7.weight", "module.base.7.bias", "module.base.10.weight", "module.base.10.bias", "module.base.12.weight", "module.base.12.bias", "module.base.14.weight", "module.base.14.bias", "module.base.17.weight", "module.base.17.bias", "module.base.19.weight", "module.base.19.bias", "module.base.21.weight", "module.base.21.bias", "module.base.24.weight", "module.base.24.bias", "module.base.26.weight", "module.base.26.bias", "module.base.28.weight", "module.base.28.bias", "module.base.31.weight", "module.base.31.bias", "module.base.33.weight", "module.base.33.bias", "module.Norm.weight", "module.Norm.bias", "module.Norm.running_mean", "module.Norm.running_var", "module.Norm.num_batches_tracked", "module.arterial.0.cfem_a.0.conv.weight", "module.arterial.0.cfem_a.0.bn.weight", "module.arterial.0.cfem_a.0.bn.bias", "module.arterial.0.cfem_a.0.bn.running_mean", "module.arterial.0.cfem_a.0.bn.running_var", "module.arterial.0.cfem_a.0.bn.num_batches_tracked", "module.arterial.0.cfem_a.1.conv.weight", "module.arterial.0.cfem_a.1.bn.weight", "module.arterial.0.cfem_a.1.bn.bias", "module.arterial.0.cfem_a.1.bn.running_mean", "module.arterial.0.cfem_a.1.bn.running_var", "module.arterial.0.cfem_a.1.bn.num_batches_tracked", "module.arterial.0.cfem_a.2.conv.weight", "module.arterial.0.cfem_a.2.bn.weight", "module.arterial.0.cfem_a.2.bn.bias", "module.arterial.0.cfem_a.2.bn.running_mean", "module.arterial.0.cfem_a.2.bn.running_var", "module.arterial.0.cfem_a.2.bn.num_batches_tracked", "module.arterial.0.cfem_a.3.conv.weight", "module.arterial.0.cfem_a.3.bn.weight", "module.arterial.0.cfem_a.3.bn.bias", "module.arterial.0.cfem_a.3.bn.running_mean", "module.arterial.0.cfem_a.3.bn.running_var", "module.arterial.0.cfem_a.3.bn.num_batches_tracked", "module.arterial.0.cfem_a.4.conv.weight", "module.arterial.0.cfem_a.4.bn.weight", "module.arterial.0.cfem_a.4.bn.bias", "module.arterial.0.cfem_a.4.bn.running_mean", "module.arterial.0.cfem_a.4.bn.running_var", "module.arterial.0.cfem_a.4.bn.num_batches_tracked", "module.arterial.0.cfem_b.0.conv.weight", "module.arterial.0.cfem_b.0.bn.weight", "module.arterial.0.cfem_b.0.bn.bias", "module.arterial.0.cfem_b.0.bn.running_mean", "module.arterial.0.cfem_b.0.bn.running_var", "module.arterial.0.cfem_b.0.bn.num_batches_tracked", "module.arterial.0.cfem_b.1.conv.weight", "module.arterial.0.cfem_b.1.bn.weight", "module.arterial.0.cfem_b.1.bn.bias", "module.arterial.0.cfem_b.1.bn.running_mean", "module.arterial.0.cfem_b.1.bn.running_var", "module.arterial.0.cfem_b.1.bn.num_batches_tracked", "module.arterial.0.cfem_b.2.conv.weight", "module.arterial.0.cfem_b.2.bn.weight", "module.arterial.0.cfem_b.2.bn.bias", "module.arterial.0.cfem_b.2.bn.running_mean", "module.arterial.0.cfem_b.2.bn.running_var", "module.arterial.0.cfem_b.2.bn.num_batches_tracked", "module.arterial.0.cfem_b.3.conv.weight", "module.arterial.0.cfem_b.3.bn.weight", "module.arterial.0.cfem_b.3.bn.bias", "module.arterial.0.cfem_b.3.bn.running_mean", "module.arterial.0.cfem_b.3.bn.running_var", "module.arterial.0.cfem_b.3.bn.num_batches_tracked", "module.arterial.0.cfem_b.4.conv.weight", "module.arterial.0.cfem_b.4.bn.weight", "module.arterial.0.cfem_b.4.bn.bias", "module.arterial.0.cfem_b.4.bn.running_mean", "module.arterial.0.cfem_b.4.bn.running_var", "module.arterial.0.cfem_b.4.bn.num_batches_tracked", "module.arterial.0.ConvLinear.conv.weight", "module.arterial.0.ConvLinear.bn.weight", "module.arterial.0.ConvLinear.bn.bias", "module.arterial.0.Co

**Comment by qijiezhao** [comment]
The supported pre-trained model is used for initializing all network, instead of only initializing the backbone.

I don't think it a good choice to finetune our model, you can use it to inference directly.

**Comment by gittigxuy** [comment]
请问一下现在仅仅支持vgg作为基础网络吗？不支持senet吗？将senet.py当中的pth下载到torch/models文件夹下的话会报维度错误

![_20181028164812](https://user-images.githubusercontent.com/15090557/47613861-5aba9f00-dad1-11e8-9323-163e6303540e.jpg)

**Comment by qijiezhao** [comment]
@gittigxuy thx for proposing the BUG,  we have fix it, you can update the code referring my latest update

**Comment by qijiezhao** [comment]
@gittigxuy It seems like that you have reproduced the detection results of cfenet300_vgg? And also successfully start to train the seresnet50, right?
