### ISSUE TITLE
测试报错

### ISSUE THREAD

**Issue by foralliance** [qijiezhao/CFENet#23]
@qijiezhao  HI

测试时，执行
`CUDA_VISIBLE_DEVICES=0 python test.py --config configs/cfenet300_vgg16.py -d COCO -m=weights/cfenet300_vgg16_coco.pth`

报错：
```
Traceback (most recent call last):
  File "test.py", line 136, in <module>
    net.load_state_dict(new_state_dict)
  File "/home/jmx/.local/lib/python2.7/site-packages/torch/nn/modules/module.py", line 721, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for CFENet:
	Unexpected key(s) in state_dict: "Norm.num_batches_tracked", "reduce1.bn.num_batches_tracked", "up_reduce1.bn.num_batches_tracked", "reduce2.bn.num_batches_tracked", "up_reduce2.bn.num_batches_tracked", "arterial.0.cfem_a.0.bn.num_batches_tracked", "arterial.0.cfem_a.1.bn.num_batches_tracked", "arterial.0.cfem_a.2.bn.num_batches_tracked", "arterial.0.cfem_a.3.bn.num_batches_tracked", "arterial.0.cfem_a.4.bn.num_batches_tracked", "arterial.0.cfem_b.0.bn.num_batches_tracked", "arterial.0.cfem_b.1.bn.num_batches_tracked", "arterial.0.cfem_b.2.bn.num_batches_tracked", "arterial.0.cfem_b.3.bn.num_batches_tracked", "arterial.0.cfem_b.4.bn.num_batches_tracked", "arterial.0.ConvLinear.bn.num_batches_tracked", "arterial.0.shortcut.bn.num_batches_tracked", "arterial.1.cfem_a.0.bn.num_batches_tracked", "arterial.1.cfem_a.1.bn.num_batches_tracked", "arterial.1.cfem_a.2.bn.num_batches_tracked", "arterial.1.cfem_a.3.bn.num_batches_tracked", "arterial.1.cfem_a.4.bn.num_batches_tracked", "arterial.1.cfem_b.0.bn.num_batches_tracked", "arterial.1.cfem_b.1.bn.num_batches_tracked", "arterial.1.cfem_b.2.bn.num_batches_tracked", "arterial.1.cfem_b.3.bn.num_batches_tracked", "arterial.1.cfem_b.4.bn.num_batches_tracked", "arterial.1.ConvLinear.bn.num_batches_tracked", "arterial.1.shortcut.bn.num_batches_tracked", "arterial.2.cfem_a.0.bn.num_batches_tracked", "arterial.2.cfem_a.1.bn.num_batches_tracked", "arterial.2.cfem_a.2.bn.num_batches_tracked", "arterial.2.cfem_a.3.bn.num_batches_tracked", "arterial.2.cfem_a.4.bn.num_batches_tracked", "arterial.2.cfem_b.0.bn.num_batches_tracked", "arterial.2.cfem_b.1.bn.num_batches_tracked", "arterial.2.cfem_b.2.bn.num_batches_tracked", "arterial.2.cfem_b.3.bn.num_batches_tracked", "arterial.2.cfem_b.4.bn.num_batches_tracked", "arterial.2.ConvLinear.bn.num_batches_tracked", "arterial.2.shortcut.bn.num_batches_tracked", "arterial.3.cfem_a.0.bn.num_batches_tracked", "arterial.3.cfem_a.1.bn.num_batches_tracked", "arterial.3.cfem_a.2.bn.num_batches_tracked", "arterial.3.cfem_a.3.bn.num_batches_tracked", "arterial.3.cfem_a.4.bn.num_batches_tracked", "arterial.3.cfem_b.0.bn.num_batches_tracked", "arterial.3.cfem_b.1.bn.num_batches_tracked", "arterial.3.cfem_b.2.bn.num_batches_tracked", "arterial.3.cfem_b.3.bn.num_batches_tracked", "arterial.3.cfem_b.4.bn.num_batches_tracked", "arterial.3.ConvLinear.bn.num_batches_tracked", "arterial.3.shortcut.bn.num_batches_tracked", "lateral.0.cfem_a.0.bn.num_batches_tracked", "lateral.0.cfem_a.1.bn.num_batches_tracked", "lateral.0.cfem_a.2.bn.num_batches_tracked", "lateral.0.cfem_a.3.bn.num_batches_tracked", "lateral.0.cfem_a.4.bn.num_batches_tracked", "lateral.0.cfem_b.0.bn.num_batches_tracked", "lateral.0.cfem_b.1.bn.num_batches_tracked", "lateral.0.cfem_b.2.bn.num_batches_tracked", "lateral.0.cfem_b.3.bn.num_batches_tracked", "lateral.0.cfem_b.4.bn.num_batches_tracked", "lateral.0.ConvLinear.bn.num_batches_tracked", "lateral.0.shortcut.bn.num_batches_tracked", "lateral.1.cfem_a.0.bn.num_batches_tracked", "lateral.1.cfem_a.1.bn.num_batches_tracked", "lateral.1.cfem_a.2.bn.num_batches_tracked", "lateral.1.cfem_a.3.bn.num_batches_tracked", "lateral.1.cfem_a.4.bn.num_batches_tracked", "lateral.1.cfem_b.0.bn.num_batches_tracked", "lateral.1.cfem_b.1.bn.num_batches_tracked", "lateral.1.cfem_b.2.bn.num_batches_tracked", "lateral.1.cfem_b.3.bn.num_batches_tracked", "lateral.1.cfem_b.4.bn.num_batches_tracked", "lateral.1.ConvLinear.bn.num_batches_tracked", "lateral.1.shortcut.bn.num_batches_tracked".
```

感觉提供的模型（**cfenet300_vgg16_coco.pth**）有问题

**Comment by liuqinglong110** [comment]
您好，我现在看不到代码，方便给个链接吗？

**Comment by qijiezhao** [comment]
你好，我删掉了repo，因为一个版本正在撰写期刊，但是从repo history还是可以找到之前的代码：https://github.com/qijiezhao/CFENet/tree/c8228dd1a9db82fbb9408232f7c737eb7b134537




Best,
Qijie Zhao


Visual Data Interpreting and Generation Lab,
Institute of Computer Science  Technology (VDIG.ICST)
Peking University


原始邮件
发件人:liuqinglong110notifications@github.com
收件人:qijiezhao/CFENetCFENet@noreply.github.com
抄送:QijieZhaozhaoqijie@pku.edu.cn; Mentionmention@noreply.github.com
发送时间:2019年1月10日(周四) 10:24
主题:Re: [qijiezhao/CFENet] 测试报错 (#23)


您好，我现在看不到代码，方便给个链接吗？

**Comment by liuqinglong110** [comment]
好的，非常感谢！发自我的华为手机-------- 原始邮件 --------主题：Re: [qijiezhao/CFENet] 测试报错 (#23)发件人：QijieZhao 收件人：qijiezhao/CFENet 抄送：liuqinglong110 ,Comment 你好，我删掉了repo，因为一个版本正在撰写期刊，但是从repo history还是可以找到之前的代码：https://github.com/qijiezhao/CFENet/tree/c8228dd1a9db82fbb9408232f7c737eb7b134537









Best,

Qijie Zhao





Visual Data Interpreting and Generation Lab,

Institute of Computer Science  Technology (VDIG.ICST)

Peking University





原始邮件

发件人:liuqinglong110notifications@github.com

收件人:qijiezhao/CFENetCFENet@noreply.github.com

抄送:QijieZhaozhaoqijie@pku.edu.cn; Mentionmention@noreply.github.com

发送时间:2019年1月10日(周四) 10:24

主题:Re: [qijiezhao/CFENet] 测试报错 (#23)





您好，我现在看不到代码，方便给个链接吗？
